krishrahul98/DSA-Library

Algorithms/Sorting/Insertion_Sort/InsertionSort.py, Algorithms/Sorting/Insertion_Sort/insertion_sort.cpp, Algorithms/Sorting/Insertion_Sort/insertion_sort_ganesh.c
#3 
C
C++
Python
3
Algorithm => Sorting => Insertion _Sort => insertion_sort.cpp
Algorithm => Sorting => Insertion _Sort => insertion_sort_ganesh.c
Algorithm => Sorting => Insertion _Sort => InsertionSort.py
example :
=> Added insertion sort programs in C, C++ and Python

Algorithms/Sorting/selection_sort/selection_sort.java
#007
1/2/3/4/...
example :
- [ x ] I've read the contribution guidelines.
- [ x ] I've referred the correct issue number.
- [ x ] I've fill up this entire template correctly.
=> selection sort

Algorithms/Sorting/Selection_Sort.py
#002
Python
1
Algorithm=>Sorting=>Selection_Sort.py
- [ -] I've read the contribution guidelines.
- [ -] I've referred the correct issue number.
- [ -] I've fill up this entire template correctly.
=> code and Algorithm of Selection_sort

Algorithms/Sorting/Bubble_Sort.py
#004
Python
1
Bubble_Sort.py
example :
- [- ] I've read the contribution guidelines.
- [-] I've referred the correct issue number.
- [- ] I've fill up this entire template correctly.
=> Bubble sort code and algorithm

Algorithms/Sorting/counting sort.c
#08
C
1
counting sort.c
example :
- [. ] I've read the contribution guidelines.
- [. ] I've referred the correct issue number.
- [ .] I've fill up this entire template correctly.
=> Counting sort in C

Algorithms/Searching/binary_search.cpp
#18 Binary Search
C++
1
Algorithm => Search_Algorithm => Binary_Search => binary_search.cpp
=> Binary Search in C++.

Algorithms/Searching/linear_search.py
#0017
Python
1
linear_search.py
example :
- [ -] I've read the contribution guidelines.
- [ -] I've referred the correct issue number.
- [ -] I've fill up this entire template correctly.
=> Linear search in Python

Algorithms/Searching/BinarySearch.java
#18 
Java
1
Algorithms => Searching => BinarySearch.java
- [Y] I've read the contribution guidelines.
- [Y] I've referred the correct issue number.
- [Y] I've fill up this entire template correctly.
=> Created BinarySearch.java

Algorithms/Searching/Binary_Search/Binary_Search.py
#18 
Python
1
Algorithm => Searching => Binary_Search => Binary_Search.py
=> Added Binary Search in Python

Algorithms/Sorting/Counting_Sort.java
#8 
Java
1
DSA-Library => Algorithm=>Sorting=>Counting_Sort.java
=> Implement=>Algorithm=>Sorting=>Counting_Sort=>Java

Algorithms/Searching/LinearSearch.java
#17
Java
1
LinearSearch.java
example :
- [. ] I've read the contribution guidelines.
- [ .] I've referred the correct issue number.
- [ .] I've fill up this entire template correctly.
=> Linear Search in java

Algorithms/Searching/Linear_Search/Linear_Search.c
#17 
C
1
Algorithms => Searching => Linear_Search => Linear_Search.c
example :
=> Linear Search in C

Algorithms/Searching/BinarySearch.c
#18
C
1
BinarySearch.c
example :
- [. ] I've read the contribution guidelines.
- [ .] I've referred the correct issue number.
- [ .] I've fill up this entire template correctly.
=> Binary search in c

Algorithms/Sorting/QuickSort.py
#5
Python
1
QuickSort.py
example :
- [. ] I've read the contribution guidelines.
- [ .] I've referred the correct issue number.
- [ .] I've fill up this entire template correctly.
=> QuickSort in python

Algorithms/Sorting/Quick_Sort/Quick_Sort.c
#005
C
1
Algorithm => Sorting => Quick _Sort => Quick_Sort.c
=> Quick Sort in C

Algorithms/Sorting/Merge_Sort/Merge_Sort.c
#6 
C
1
Algorithms => Sorting=> Merge_Sort => Merge_Sort.c
example :
=> Merge Sort in C

Algorithms/Sorting/Heap_Sort/Heap_Sort.c, Algorithms/Sorting/Heap_Sort/Heap_Sort.cs
#007
C and c#
2
Algorithm => Sorting_Algorithm => Heap_Sort => Heap_Sort.cs
Algorithm => Sorting_Algorithm => Heap_Sort => Heap_Sort.c
example :
=> added Heap sort with c and c#

Algorithms/Sorting/Quick_Sort/Quick_Sort.java
#005
Java
1
Algorithm => Sorting_Algorithm => Quick_Sort=> Quick_Sort.java
example :
=> added quick sort in java

Algorithms/Sorting/Selection_Sort/Selection_Sort.cs
#002
C#
1
Algorithm => Sorting Algorithm=> Selection_Sort => SelectionSort.cs
example :
=> added selection sort with c#

Algorithms/Sorting/Bubble_Sort/Bubble_Sort.java
#004
Java
1
Algorithm => Sorting algorithm => Bubble_Sort => Bubble_Sort.java
example :
=> added bubble sort in java

Algorithms/Searching/Linear_Search/Linear_Search.cpp
#17
C++
1
DSA-Library=>Algorithms=>Searching=>Linear_Search=>Linear_Search.cpp
example :
=> Linear_Search.cpp

Algorithms/Sorting/Redix_sort/Radix_sort.java
#33 
Java
1
DSA-Library => Algorithms => Sorting => Radix Sort =>  Radix_sort.java
example :
- [yes ] I've read the contribution guidelines.
- [ yes] I've referred the correct issue number.
- [ yes] I've fill up this entire template correctly.
=> RadixSort algorithm added in java

Data_Structures/Array/reverse_array.py
#42 
Python
1
DSA-Library => Data_Structures =>Array=>reverse_array.py
=> file added

Algorithms/Searching/Jump_Search/jump_search.py
#020
Python
1
Algorithms, Searching, Jump_Search, jump_search.py
example :
- [ X ] I've read the contribution guidelines.
- [ X ] I've referred the correct issue number.
- [ X ] I've fill up this entire template correctly.
=> I added the jump search algorithm for python

Data_Structures/Tree/BinarySearchTree.c
C
1
Data_Structures/Tree/BinarySearchTree.c
=> Added Binary Search Tree Implementation

Algorithms/Sorting/Counting_Sort/Counting_Sort.cpp
#008
C++
1
Algorithm => Sorting => Counting_Sort => Counting_Sort.cpp
=> Counting sort in C++

Algorithms/Sorting/Quick_Sort/quick_sort.cpp
@krishrahul98 
#5 
C++
1
Algorithms => Sorting => Quick_Sort => quick_sort.cpp
example :
=> Added quick sort program in C++

Algorithms/Searching/Linear_Search/LinearSearch.cs
#17 
C#
1
Algorithm => Search_Algorithm => Linear_Search => Linear_Search.cs
=> Added Linear Search Algorithm in C#

Data_Structures/Array/Reverse_Array_AlgorithmName.c
#042
C
1
Data_Structures => Array => Reverse_Array_AlgorithmName.c
=> Create Array Reversal Algorithm

Data_Structures/Array/Rotate_Array_L.py
#40 
Python
1
Data_Structures => Array => Rotate_Array_L.py
=> Added Array Rotation (left or right) for Arrays in Python

Data_Structures/Array/Reverse_Array.java
#42 
Java
1
Data_Structures => Array => Reverse_Array.java
=> Added array reversal in java

Algorithms/Sorting/Bubble_Sort/Bubble_Sort.js
#4 
Javascript
1
Algorithms/Sorting/Bubble_Sort/Bubble_Sort.js
=> Added Bubble Sort in Javascript

Data_Structures/LinkedList/reverse_list.cpp
Reverse a given linked list and return the head of the list.
#007
1
DSA-Library => data_structures => linkedlist=>reverse_list.cpp
example :
=> reverse_linked_list

Data_Structures/Tree/BST/flatten_binary_tree.cpp
=> Flatten binary tree to linked list

Algorithms/Sorting/Bubble_Sort/Bubble_Sort.cpp
#4 
C++
1
Algorithms => Sorting => Bubble_Sort => Bubble_Sort.cpp
=> Added bubble sort C++

Data_Structures/Queue/Queue.cs, Data_Structures/Stack/Stack.cs
#63 and #64 
C#
2
Data_Structures=> Queue => Queue.cs
Data_Structures=> Stack=> Stack.cs
=> Adding Queue.cs and Stack.cs

Data_Structures/Tree/BST/binary_search_tree.cpp
#65 
C++
1
Data_Structures => Tree => BST => binary_search_tree.cpp
example :
=> Added binary search tree program in C++

.theia/launch.json, Algorithms/Sorting/Insertion_Sort/insertion_sort.cs
#003
C#
1
Algorithm => Sorting => Insertion_Sort => insertion_sort.cs
example :
=> I added the Insertion  sort for C#

Data_Structures/Queue/Queue_Implementation.java
#64 
Java
1
Data_Structures => Queue => Queue_Implementation.Java
=> added queue implementation in java

Algorithms/Greedy/Fractional_knapack_greedy.py
Language Opted 
Python
Number of files added or updated 
1
Name of these files 
Algorithm => Greedy_Algorithm => Fractional_knapsack => Fractional_knapsack_greedy.py
Checklist
- [Yes ] I've read the contribution guidelines.
- [ Yes] I've referred the correct issue number.
- [Yes ] I've fill up this entire template correctly.
=> Fractional Knapsack using Python.

Data_Structures/Array/Rotate_Array_L.java
#40 
java
1
Data_Structures => Array => Rotate_Array_L.java
=> added array rotation in java

Data_Structures/Array/Rotated_Array_Search.py
No issue
Python.
1
Data_Structures => Array => Rotated_Array_Search.py
=> added rotated array search in python

Algorithms/Sorting/Merge_Sort/merge_sort.py, Algorithms/Sorting/Shell_Sort/readme.md, Algorithms/Sorting/Shell_Sort/shell_sort.cpp, Algorithms/Sorting/Shell_Sort/shell_sort.py
#35 
C++ & Python
3
Algorithms => Sorting => Shell_Sort => shell_sort.py
Algorithms => Sorting => Shell_Sort => shell_sort.cpp
=> Shell Sort

Algorithms/Sorting/Shell_Sort/ShellSort.c
#35
C
1
Algorithms => Sorting => Shell_Sort => ShellSort.c
=> Added Shell Sort in C

Data_Structures/Array/array_rotate.cpp
#40 
C++
1
Data_Structures/Array/array_rotate.cpp
=> C++ Program to Left/Right rotate an array

Data_Structures/Stack/Implementation/Stack.cpp, Data_Structures/Stack/Implementation/Stack.py
#63
C++ and Python
2
Data_Structures => Stack => Implementation => Stack.cpp
Data_Structures => Stack => Implementation => Stack.py
=> Added stack implementation in C++ and Python

Data_Structures/Queue/Queue_Implementation.c
#64 
C
1
Data_Structures => Queue => Queue_Implementation.c
=> Create Queue Implementation in C

Data_Structures/LinkedList/Reverse_List/reverse_list.cs
#81
C#
1
Data_Structures => LinkedList => Reverse_List => reverse_list.cs
=> Add reversing linked list C# code.

Data_Structures/Queue/Queue_Implementation.java
#064
Java
1
Data_Structures => Queue => Queue_Implementation.java
example :
=> Queue implementation in java

Data_Structures/LinkedList/Rotate_Linked_List/rotate_linked_list.js, Data_Structures/LinkedList/Rotate_Linked_List/rotate_linked_list.py
Rotate Linked List:
#82 
Python & JavaScript
2
Data_Structures => LinkedList => Rotate_Linked_List =>rotate_linked_list.py
Data_Structures => LinkedList => Rotate_Linked_List =>rotate_linked_list.js
=> Rotate Linked List

Data_Structures/Tree/BST/Implementation/BST_tree_Itretive_And_Recursive_Treversal.c
=> Add BST tree itrative and recursive treversal

Data_Structures/Array/Rotated_Array_Search/Rotated_Array_Search.c
- for user input arrays
- searches through indices
- binary searching technique
#043
C
1
Data_Structures => Array => Rotated_Array_Search => Rotated_Array_Search.c
example :
=> Added Rotated Array Search Code in C

Data_Structures/Stack/Implementation/Stack.c
#63
C
1
Data_Structures => Stack => Implementation => Stack.c 
=> Added Stack Implementation in C

Algorithms/Sorting/Shell_Sort/ShellSort.java
- sorts user entered arrays
- displays array results before and after sorting
#035
Java
1
Algorithm => Sorting => Shell _Sort => ShellSort.java
example :
=> Added Shell Sort code in Java

Algorithms/Sorting/Quick_Sort/quicksort.js
#5 
Javascript
1
Algorithm => Sorting => Quick _Sort => quicksort.js
=> Added quick sort implementation in JavaScript

Data_Structures/Stack/Implementation/Stack.js
#63 
JavaScript
1
Data_Structures => Stack => Implementation => Stack.js
=> Implementation of Stack in JavaScript

Data_Structures/Array/Reverse_Array/reverse_array.js
#42 
JavaScript
1
Data_Structures =>Array =>Reverse_Array=>reverse_array.js
=> Reversing An Array in JavaScript

Algorithms/Sorting/Bubble_Sort/Bubble_Sort.c
#04
C
1
Algorithms => Sorting => Bubble_Sort => Bubble_Sort.c
=> Bubble Sort Implementation in C

Data_Structures/Array/Rotate_Array/rotate_array.js, Data_Structures/Queue/Implementation/Queue_Implementation.js
#40 
JavaScript
1
Data_Structures => Array => Rotate_Array => rotate_array.js 
=> Array Rotation & Queue Implementation in JavaScript

Data_Structures/Tree/Binary_Tree_Traversal/Binary_Tree_Traversal_Recursive.cpp
#93 
C++
1
Data_Structures => Tree => Binary_Tree => Binary_Tree_Traversal_Recursive.cpp
=> Preorder, InOrder and PreOrder Binary Tree Traversal in C++ (Recursive)

Data_Structures/LinkedList/Reverse_List/reverse_LinkedList.js, Data_Structures/LinkedList/Reverse_List/reverse_LinkedList.py
#81 
Python & JavaScript
2
Data_Structures => LinkedList => Reverse_List => reverse_LinkedList.js
Data_Structures => LinkedList => Reverse_List => reverse_LinkedList.py
=> Reverse Linked List

Algorithms/Searching/Binary_Search/binary_search.js
#18 
Javascript
1
Algorithms => Searching => Binary_Search => Binary_Search.js
=> Added Binary Search Implemenation in Javascript

Algorithms/Searching/Jump_Search/JumpSearch.java
- searches elements in user input array
- Jump search using suitable jump step
#020
Java
1
Algorithms => Searching => Jump_Search => JumpSearch.java
example :
=> Add Jump Search code in Java

Data_Structures/LinkedList/Merge_two_sorted_lists/mergeLists.cpp
Added program for Merging two sorted LinkedLists in C++.
#120 
C++
1
Data structures => Linked Lists =>Merge_two_sorted_lists ... => ... =>  mergeLists.cpp
example :
- [] I was assigned for this otherwise my **PR will be rejected**.
- [] I've read the contribution guidelines.
- [] I've referred the correct issue number.
- [] I've filled up this entire template correctly.
=> Merge two sorted Linked lists

Data_Structures/LinkedList/Rotate_Linked_List/rotate_linked_list.cs
#82 
C#
1
Data_Structures => LinkedList => Rotate_Linked_List =>  rotate_linked_list.cs
=> Add C# code for linked list rotation.

Algorithms/Searching/Binary_Search/BinarySearch.cs
#18 
C#
1
Algorithms => Searching => Binary_Search => BinarySearch.cs
=> Add C# code for binary search

Data_Structures/Array/Rotate_Array/Rotate_Array.c
#40 
C
1
Data_Structures => Array => Rotate_Array =>Rotate_Array.c
=> Array Rotation in C

Data_Structures/LinkedList/Merge_two_sorted_lists/mergeLists.js
#120 
JavaScript
1
Data_Structures => LinkedList => Merge_two_sorted_lists => mergeList.js
=> Merge Two Sorted List in JavaScript

Data_Structures/LinkedList/Merge_two_sorted_lists/mergeLists.py
#120  
Python
1
Data_Structures => LinkedList => Merge_two_sorted_lists => mergeLists.py
=> Merge Two Sorted Linked Lists in Python

Data_Structures/Array/Largest_Sum_Contiguous_Subarray/LSCA.py
#119 
Python
1
Data_Structures => Array => Largest_Sum_Contiguous_Subarray => LSCA.py
=> Largest Sum Contiguous Subarray in Python

Data_Structures/LinkedList/Reverse_List/reverse_linkedlist.c
=> Added program to reverse a single linked list using C

Algorithms/Searching/Interpolation_Search/InterpolationSearch.java, Algorithms/Searching/Interpolation_Search/interpolation_search.c
#019
C, Java
2
Algorithms => Searching => Interpolation_Search => interpolation_search.c
Algorithms => Searching => Interpolation_Search => InterpolationSearch.java
example :
=> Add Interpolation Search in C and Java

Project_Euler/1-Multiple_Of_3_And_5/1-Multiple_Of_3_And_5.cpp, Project_Euler/2-Even_Fibonacci_Numbers/2-Even_Fibonacci_Numbers.cpp, Project_Euler/3-Largest_Prime_Factor/3-Largest_Prime_Factor.cpp, Project_Euler/4-Largest_Palindrome_Product/4-Largest_Palindrome_Product.cpp, Project_Euler/5-Smallest_multiple/5-Smalllest_multiple.cpp
#126 
C++
5
Project_Euler => 1-Multiple_Of_3_And_5 => 1-Multiple_Of_3_And_5.cpp
Project_Euler => 2-Even_Fibonacci_Numbers => 2-Even_Fibonacci_Numbers.cpp
Project_Euler => 3-Largest_Prime_Factor => 3-Largest_Prime_Factor.cpp
Project_Euler => 4-Largest_Palindrome_Product => 4-Largest_Palindrome_Product.cpp
Project_Euler => 5-Smallest_multiple => 5-Smalllest_multiple.cpp 
=> [1-5] project Euler Problems in C++

Data_Structures/Queue/Implementation/Queue_Implementation.py, Project_Euler/1-Multiple_Of_3_And_5/1-Multiple_Of_3_And_5.js, Project_Euler/2-Even_Fibonacci_Numbers/2-Even_Fibonacci_Numbers.cpp, Project_Euler/2-Even_Fibonacci_Numbers/2-Even_Fibonacci_Numbers.js, Project_Euler/3-Largest_Prime_Factor/3-Largest_Prime_Factor.js, Project_Euler/4-Largest_Palindrome_Product/4-Largest_Palindrome_Product.js, Project_Euler/5-Smallest_multiple/5-Smallest_multiple.js
#64 
Python
1
Data_Structures => Queue => Implementation => Queue_Implementation.py
=> Queue Implementation in Python

Data_Structures/LinkedList/Merge_two_sorted_lists/mergeLists.c
#120 
C
1
Data_Structures => LinkedList =>Merge_two_sorted_lists => mergeLists.c
=> Merge two sorted linked Lists in C

Data_Structures/Tree/BST/Binary_Search_Tree.java, Data_Structures/Tree/BST/Binary_Search_Tree.py
#65 
Python/Java
2
Data_Structures => Tree => BST_Implementation => Binary_Search_Tree.java
Data_Structures => Tree => BST_Implementation => Binary_Search_Tree.py
=> created BST implementation in Java and python

Algorithms/Searching/Linear_Search/Linear_Search.js
#17 
JavaScript
1
Algorithms => Searching => Linear_Search => Linear_Search.js
=> added algorithm for linear search using javascript

Data_Structures/Array/Largest_Sum_Contiguous_Subarray/LSCA.java
Largest_Sum_Contiguous_Subarray in Java
#119
Java
1
Data_Structures => Array => Largest_Sum_Contiguous_Subarray => LSCA.java
=> Largest_Sum_Contiguous_Subarray in Java

Algorithms/Sorting/Selection_Sort/Selection_Sort.js
=> Selection_Sort in JavaScript

Algorithms/Sorting/Insertion_Sort/Insertion_Sort.js
=> Insertion_Sort in JavaScript

.vscode/settings.json, Algorithms/Sorting/Radix_Sort/Radix_Sort.cpp
#33
C++
1
Algorithms => Sorting => Radix_Sort => Radix_Sort.cpp
=> added algorithm for radix sort using cpp

Project_Euler/1-Multiple_Of_3_And_5/1-Multiple_Of_3_And_5.c
#126 
C
1
Project_Euler => 1-Multiple_Of_3_And_5 =>1-Multiple_Of_3_And_5.c
example :
=> Implemented Project_Euler_1 Multiple_Of_3_And_5 in C

Algorithms/Sorting/Merge_Sort/Merge_Sort.js
=> Merge_Sort in JavaScript

Project_Euler/21-Amicable_Numbers/AmicableNumbers.java, Project_Euler/21-Amicable_Numbers/Amicable_Numbers.c
#133
C, Java
2
Project_Euler => 21-Amicable_Numbers => Amicable_Numbers.c
Project_Euler => 21-Amicable_Numbers => AmicableNumbers.java
example :
=> Add Amicable Number code in C, Java: #ProjectEuler21

Data_Structures/Tree/Binary_Tree_Traversal/Binary_Tree_Traversal_Iterative.cpp
#93 
C++
1
Data Structures => Tree => Binary_Tree_Traversal => Binary_Tree_Traversal_Iterative.cpp
=> C++ Iterative Binary Tree Pre/Post/In-Order Traversals

Algorithms/Sorting/Bucket_Sort/Bucket_Sort.py, Algorithms/Sorting/counting sort.cpp
=> added Bucket sort python

Algorithms/Sorting/Quick_Sort/RandQuickSort.java
#147 
Java
1
Algorithms => Sorting => Quick_Sort => RandQuickSort.java
=> Randomized Quick Sort(Java)

Algorithms/Searching/Jump_Search/jump-search.js
#020
JavaScript
1
Algorithms => Searching => Jump_Search => jump-search.js
=> Jump search in JS

Data_Structures/Tree/Binary_Tree_Level_Order_Traversal_Spiral/Binary_Tree_Level_Order_Traversal_Spiral.c
#164
C
1
Data_Structure => Tree => Binary_Tree_Level_Order_Traversal_Spiral => Binary_Tree_Level_Order_Traversal_Spiral.c
example :
=> add binary tree level order traversal, spiral mode

Data_Structures/Tree/Binary_Tree_Traversal/ Binary_Tree_Level_Order_Traversal.js
#163 
Javascript
1
Data_Structure => Tree => Binary_Tree_Level_Order_Traversal => Binary_Tree_Level_Order_Traversal.js
=> binary tree level order traversal in JS implemented

Data_Structures/Tree/Binary_Tree_Traversal/Binary_Tree_Level_Order_Traversal.cpp
#163 
C++
1
Data_Structures=>Tree=>Binary_Tree_Traversal=>Binary_Tree_Level_Order_Traversal.cpp
=> Added Binary Tree Level Order Traversal in CPP

Data_Structures/LinkedList/Merge_two_sorted_lists/mergeList.cs
#120 
C#
1
Data_Structures=>LinkedList=>Merge_two_sorted_lists=>mergeList.cs
=> Added Merge Two Sorted LL in C#

Data_Structures/Tree/Binary_Tree_Traversal/BinaryTree_Traversal_Recursive.cs
#93 
C#
1
Data_Structures=>Tree=>Binary_Tree_Traversal=>BinaryTree_Traversal_Recursive.cs
=> Added BinaryTree_Traversal_Recursive in C#

Data_Structures/Array/Largest_Sum_Contiguous_Subarray/LSCA.c
#119 
C
1
Data_Structures=>Array=>Largest_Sum_Contiguous_Subarray=>LSCA.c
=> Implemented Largest Sum Contiguous Subarray in C

Data_Structures/Array/Rotated_Array_Search/Rotated_Array_Search.cs
#43 
C#
1
Data_Structures => Array => Rotated_Array_Search => Rotated_Array_Search.cs
=> Add C# code for Sorted and Rotated Array Search.

Data_Structures/Array/Largest_Sum_Contiguous_Subarray/LSCA.js
#119 
Javascript
1
Data_Structures => Array => Largest_Sum_Contiguous_Subarray=> LSCA.js
=> LSCA for JS implemented

Algorithms/Sorting/Bubble_Sort/Bubble_Sort.cs
#4  
C#
1
Algorithms => Sorting => Bubble_Sort => Bubble_Sort.cs
example :
=> Add Bubble Sort Implementation in C#

Algorithms/Sorting/Quick_Sort/Quick_Sort.cs
#5 
C#
1
Algorithms => Sorting => Quick_Sort => Quick_Sort.cs
example :
=> Add Quick Sort Implementation using C#

Algorithms/Sorting/Merge_Sort/Merge_Sort.cs
- array size taken taken as a random positive integer.
- user array input.
- Merge Sort applied recursively.
#006
C#
1
Algorithms => Sorting => Merge _Sort => Merge_Sort.cs
example :
Algorithms => Sorting => Merge _Sort => Merge_Sort.cs
=> Add Merge Sort code in C#

Algorithms/Sorting/Radix_Sort/Radix_Sort.cs
#33 
C#
1
Algorithms => Sorting => Radix_Sort => Radix_Sort.cs
example :
=> Add Radix Sort using C#

Algorithms/Backtracking/StringPermute/StringPermute.cpp
#186 
C++
1
Algorithms => Backtracking => StringPermute =>  StringPermute.cpp
example :
=> Adding StringPermute.cpp

Data_Structures/LinkedList/Linked_List_Cycle/FloydCycle.java
#001
C/C++/Python/Java/... => Java
1/2/3 => 1
Algorithms => LinkedList => Linked_List_Cycle => FloydCycle.java
- [ Y] I was assigned for this otherwise my **PR will be rejected**.
- [ Y] I've read the contribution guidelines.
- [ Y] I've referred the correct issue number.
- [ Y] I've filled up this entire template correctly.
=> Linked list cycle finding algorithm using floyd's cycle finding algorithm written in Java

Data_Structures/LinkedList/Linked_List_Cycle/Linked_List_Cycle.c
#187
C
1
Datastructures => Linkedlist => Linked_List_Cycle => Linked_List_Cycle.c
=> Added Linked_List_Cycle in C

Data_Structures/Tree/Binary_Tree_Level_Order_Traversal_Spiral/Binary_Tree_Level_Order_Traversal_Spiral.cpp
#164
C++
1
Data_Structure => Tree => Binary_Tree_Level_Order_Traversal_Spiral => Binary_Tree_Level_Order_Traversal_Spiral.cpp
=> Added Binary_Tree_Level_Order_Traversal_Spiral in C++

Data_Structures/LinkedList/Linked_List_Cycle/Linked_List_Cycle.cpp
#187 
C++
1
Datastructures => LinkedList => Linked_List_Cycle =>  Linked_List_Cycle.cpp
example :
=> Linked list cycle in cpp

Data_Structures/LinkedList/Linked_List_Cycle/FloydCycle.py
#187 
Python
1
Datastructures => Linkedlist => Linked_List_Cycle => FloydCycle.py
=> floyds-cycle-python

Algorithms/Backtracking/StringPermute/StringPermute.py
#186 
Python
1
Algorithms => Backtracking => StringPermute => StringPermute.py
=> permutestringpython

Data_Structures/LinkedList/Linked_List_Cycle/FloydCycle.js
#187
Javascript
1
(shows two commits because I was trying to figure out how to update my fork)
Data_Structures => LinkedList => Linked_List_Cycle => FloydCycle.js
=> Floyd's Linked List Loop Detection Algorithm for Javascript

Data_Structures/Array/Inversion_Count/Inversion_Count.py
#195
Python
1
Data_Structures => Array => Inversion_count => Inversion_Count.py
=> Added Inversion_Count in Python

.gitignore, Data_Structures/Array/Inversion_Count/inversion_count.js
#195 
JavaScript
2
Data_Structures => Array => Inversion_Count => inversion_count.js
=> feat: inversionCount in js

Algorithms/Sorting/Quick_Sort/RandomizedQuicksort.cs, Algorithms/Sorting/Quick_Sort/Randomized_Quicksort.c
#147
C/C#
2
Algorithms => Sorting => Quick_Sort => RandomizedQuicksort.cs
Algorithms => Sorting => Quick_Sort => Randomized_Quicksort.c
example :
=> Add Randomized Quick Sort in C, C#

Data_Structures/Array/Inversion_Count/Inversion_Count.cpp
#195 
C++
1
Data_Structures => Array => Inversion_Count => Inversion_Count.cpp
example :
=> Adding inversion count in cpp

Data_Structures/Array/Inversion_Count/Inversion_Count.java
#195
Java
1
Data_Structures => Array => Inversion_count => Inversion_Count.java
=> Added Inversion_Count in java

Algorithms/Sorting/Insertion_Sort/insertion_sort.go, Data_Structures/Queue/Implementation/Implementing Queus.cpp
1
C++
1/2/3
Data_Structures/Queue/Implementation/Implementing Queus.cpp
example :
Data STructures=> Queues => Implementing queues alternative => mplementing Queus.cpp
=> Implementing Queues Alternative

Algorithms/Sorting/Shell_Sort/Shell_Sort.js
##35
C/C++/Python/Java/... => Javascript
1/2/3
1
Algorithms => Sorting => Shell_Sort => Shell_Sort.js
- [Y ] I was assigned for this otherwise my **PR will be rejected**.
- [ Y] I've read the contribution guidelines.
- [ Y] I've referred the correct issue number.
- [ Y] I've filled up this entire template correctly.
=> Implement Shell Sort algorithm in javascript

Algorithms/Backtracking/StringPermute/StringPermute.c
Added String Permutation by Backtracking Approach in C
=> StringPermutation in C

Project_Euler/21-Amicable_Numbers/Amicable_Numbers.cs
#133 
C#
1
DSA-Library => Project_Euler => 21-Amicable_Numbers => Amicable_Numbers.cs
example :
=> Sum of Amicable Numbers smaller than 10000

Algorithms/Sorting/Heap_Sort/heapS.c
#7 
C
1
Algorithm => Sorting_Algorithm => Heap_Sort => heapS.c
=> algorithm for Heap-Sort in C

Algorithms/Backtracking/StringPermute/StringPermute.js
#186 
Javascript
1
Algorithms => Backtracking => StringPermute => StringPermute.js
=> implemented backtracking StringPermute for JS

Algorithms/Sorting/Heap_Sort/Heap_Sort.cpp
#007
C++
1
Algorithms => Sorting => Heap_Sort => Heap_Sort.cpp
=> Heap sort in C++

Algorithms/Greedy/Fractional_Knapsack/partial_knapsack.java
though its a little cumbersome then greedy but for a better understanding of Dp its a good question.
#001
1/2/3
example :
=>  I have tried solving fractional knapsack using Dp

Data_Structures/Array/Inversion_Count/inversion_Count.cpp
=> Adding inversion-count in cpp simple approach

Algorithms/Sorting/Heap_Sort/Heap_Sort.js
#7 
Javascript
1
Algorithms => Sorting => Heap_Sort => Heap_Sort.js
- [ x] I was assigned for this otherwise my **PR will be rejected**.
- [x ] I've read the contribution guidelines.
- [x ] I've referred the correct issue number.
- [x ] I've filled up this entire template correctly.
=> Adding JS Heapsort algorithm - #7

Algorithms/DP/Longest_Common_Subsequence/LCS.c, Algorithms/DP/Longest_Common_Subsequence/LCS.java
#220 
C/Java
2
Algorithms => DP => Longest_Common_Subsequence => LCS.c
Algorithms => DP => Longest_Common_Subsequence => LCS.java
example :
=> Add Longest Common Substring Code in C, Java

Algorithms/DP/Longest_Common_Subsequence/longestCommonSubsequence.js
#220
Javascript
1
Algorithms => DP => Longest_Common_Subsequence => longestCommonSubsequence.js
- [x ] I was assigned for this otherwise my **PR will be rejected**.
- [ x] I've read the contribution guidelines.
- [ x] I've referred the correct issue number.
- [x ] I've filled up this entire template correctly.
=> Adding longest common substring for javascript

Algorithms/DP/Longest_Common_Subsequence/LCS.py
#220 
Python
1
`DSA-Library/Algorithms/DP/Longest_Common_Subsequence/LCS.py`
example :
=> Longest Common Susbequence code added in Python

Algorithms/Sorting/Tim_Sort/tim_sort.py
#240
Python
1
``DSA-Library/Algorithms/Sorting/Tim_Sort/tim_sort.py``
example :
=> Add Tim Sort implementation in Python

Algorithms/Sorting/Counting_Sort/other_counting_sort_implemtation.cpp
Structuring files in the directory: ``DSA-Library/Algorithms/Sorting/Counting_Sort``
=> Move counting_sort.cpp into Counting_Sort directory with a better name

.gitignore, Algorithms/Sorting/Tim_Sort/tim_sort.c
#240
C
1
``DSA-Library/Algorithms/Sorting/Tim_Sort/tim_sort.c``
=> Add Tim Sort implementation in C

Project_Euler/21-Amicable_Numbers/Amicable_Numbers.js
#133 
JavaScript
1
DSA-Library => Project_Euler => 21-Amicable_Numbers => Amicable_Numbers.js
example :
=> Added Amicable_Numbers.js (JavaScript)

Algorithms/Bit-Manipulation/UTF-8 encoding checker/UTF-8_encdng_chckr.py
#228
Python
1
Algorithms => Bit-Manipulation => UTF-8 encoding checker => UTF-8_encdng_chckr.py
=> Add invalid code point checking in python

Algorithms/Sorting/Tim_Sort/tim_sort.cpp
#240
C++
1
``DSA-Library/Algorithms/Sorting/Tim_Sort/tim_sort.cpp``
I will soon write a class ``TimSort`` for Cpp as well. Or maybe, others may find this a good place to start implementing in their own way in C++.
=> Add Tim Sort implementation in C++(Copy code from the C implementation)

Algorithms/Sorting/Tim_Sort/TimSort.java, Algorithms/Sorting/Tim_Sort/tim_sort.js, Data_Structures/Array/Inversion_Count/inversion_Count (2).cpp, Data_Structures/Array/Inversion_Count/inversion_Count.cpp
#240
JavaScrpit
4
Algorithms => Sorting => Tim_Sort => tim_sort.js
Algorithms => Sorting => Tim_Sort => Tim_Sort.java
=> Add Tim Sort Implementation in JS 

Algorithms/Sorting/Binary_Insertion_Sort/BinaryInsertionSort.java
#254 
Java
1
Algorithms => Sorting => Binary_Insertion_Sort => BinaryInsertionSort.java
example :
=> adding Binary Insertion Sort java implementation

Data_Structures/Hashing/Node.java, Data_Structures/Hashing/SeperateChaining.java
#262
Java
1
DSA-Library => Data_Structures => Hashing => SeperateChaining.java
=> Add Seperate Chaining in Java | Issue : #262

Data_Structures/Hashing/SeperateChaining.cpp
#263
C++
1
Data_Structures => Hashing => SeperateChaining.cpp
=> Add Seperate Chaining in Cpp | Issue : #262

Algorithms/Sorting/Binary_Insertion_Sort/binary_insertion_sort.py
issue: #267 
python
Number of files added:1
DSA-Library/Algorithms/Sorting/Binary_Insertion_Sort/binary_insertion_sort.py
- [ x] I was assigned for this otherwise my **PR will be rejected**.
- [x ] I've read the contribution guidelines.
- [ x] I've written code by myself. **No Plagiarism allowed**
- [ x] I've referred the correct issue number.
- [ x] I've filled up this entire template correctly.
=> Add python binary insertion sort implementation

Algorithms/Sorting/Binary_Insertion_Sort/binaryInsertionSort.js
#254
JavaScript
1
Algorithms => Sorting => Binary_Insertion_Sort => binaryInsertionSort.js
=> adding Binary Insertion Sort Algorithm JavaScript implementation

Algorithms/Sorting/Binary_Insertion_Sort/binaryInsertionSort.cs, Algorithms/Sorting/Binary_Insertion_Sort/binaryInsertionSort.js
#254 
C#
1
Algorithms => Sorting => Binary_Insertion_Sort => binaryInsertionSort.cs
This algorithm has been tested with the following script that I wrote:
```c#
int times = 1;
bool passed = true;
Random rnd = new Random();
do
{
int len = (int)rnd.Next(10) * 100;
double[] arr = new double[len];
for (int index = 0; index < len; index++)
{
arr[index] = rnd.Next();
}
double[] clnArr = (double[])arr.Clone();
Array.Sort(clnArr);
double[] binarysortedarray = binaryInsertionSort(arr);
for (int index = 0; index < arr.Length; index++)
{
passed = binarysortedarray[index] == clnArr[index];
if (!passed)
{
break;
}
}
if (passed)
{
Console.WriteLine("Test case N {0:D} Passed ✅\n ------", times);
}
else
{
Console.WriteLine("----- Error on case {0:D} -----", times);
Console.WriteLine("[{0}]", …
```
=> adding Binary Insertion Sort Algorithm C# implementation #254

Algorithms/DP/Kadane-algorithm/index.ts
#285
TypeScript
1
Algorithms => DP => Kadane-algorithm => index.ts
example :
=> feat: kadane's algorithm - typescript

circular queue using reference
=> Create circular queue using reference

Algorithms/DP/Longest_Increasing_Subsequence/longestIncreaseSubsequence.cpp, Algorithms/README.md
#001
C++
2
Algorithms => README.md
Algorithms => DP =>Longest_Increassing_Subsequence =>  longestIncreaseSubsequence.cpp
example :
=> Added code on Longest Increasing subsequence
